name: Deploy ArcSat CRM to Azure

on:
  push:
    branches:
      - main
      - copilot/set-up-copilot-instructions
    paths:
      - 'frontend/**'
      - 'src/**'
      - 'package.json'
      - '.github/workflows/azure-deploy.yml'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: arcsat-crm
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy ArcSat CRM
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install backend dependencies
      run: npm ci

    - name: Install frontend dependencies
      run: |
        cd frontend/arcsat-landing
        npm ci

    - name: Build frontend Next.js
      run: |
        cd frontend/arcsat-landing
        npm run build

    - name: Create deployment package
      run: |
        zip -r deployment.zip \
          src/ \
          frontend/arcsat-landing/.next/ \
          frontend/arcsat-landing/public/ \
          frontend/arcsat-landing/next.config.ts \
          frontend/arcsat-landing/package.json \
          package.json \
          package-lock.json \
          -x "*.git*" \
          -x "*node_modules*" \
          -x "*.env*"

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: deployment.zip

    - name: Configure App Settings with Secrets
      run: |
        az webapp config appsettings set \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group rg-arcsat-crm \
          --settings \
            NODE_ENV=production \
            PORT=8080 \
            MONGODB_URI="${{ secrets.MONGO_ATLAS_URI }}" \
            JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            CLOUDFLARE_API_TOKEN="${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            EMAIL_HOST=smtp.porkbun.com \
            EMAIL_PORT=587 \
            EMAIL_USER=nicolas@avila.inc \
            FRONTEND_URL=https://crm.avila.inc \
            WEBSITE_NODE_DEFAULT_VERSION="~20" \
            SCM_DO_BUILD_DURING_DEPLOYMENT=true

    - name: Restart Web App
      run: |
        az webapp restart \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group rg-arcsat-crm

    - name: Logout from Azure
      run: az logout
