name: ArcSat CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      skip_deploy:
        description: 'Skip deployment'
        required: false
        type: boolean
        default: false

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: Build Frontend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: './frontend/arcsat-landing/package-lock.json'

    - name: Install Dependencies
      working-directory: ./frontend/arcsat-landing
      run: npm ci

    - name: Lint Application
      working-directory: ./frontend/arcsat-landing
      run: npm run lint --if-present
      continue-on-error: true

    - name: Build Application
      working-directory: ./frontend/arcsat-landing
      run: npm run build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: ./frontend/arcsat-landing/out
        retention-days: 7

  deploy-frontend:
    runs-on: ubuntu-latest
    name: Deploy Frontend to Azure
    needs: build-frontend
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'workflow_dispatch' && !inputs.skip_deploy)
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: ./frontend/arcsat-landing/out

    - name: Check if Azure token is available
      id: check-secret
      run: |
        if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then
          echo "has_token=false" >> $GITHUB_OUTPUT
          echo "⚠️ Azure Static Web Apps API token is not configured"
        else
          echo "has_token=true" >> $GITHUB_OUTPUT
          echo "✓ Azure Static Web Apps API token is available"
        fi

    - name: Deploy to Azure Static Web Apps
      if: steps.check-secret.outputs.has_token == 'true'
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: upload
        app_location: ./frontend/arcsat-landing/out
        skip_app_build: true
        skip_api_build: true

    - name: Deployment skipped
      if: steps.check-secret.outputs.has_token == 'false'
      run: |
        echo "::warning::Deployment to Azure Static Web Apps was skipped because AZURE_STATIC_WEB_APPS_API_TOKEN is not configured."
        echo "To enable deployment, add the AZURE_STATIC_WEB_APPS_API_TOKEN secret in repository settings."
        echo "See: https://docs.microsoft.com/azure/static-web-apps/get-started-portal"

  build-backend:
    runs-on: ubuntu-latest
    name: Build and Test Backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Type Check
      run: npm run typecheck

    - name: Lint Backend
      run: npm run lint --if-present
      continue-on-error: true

    - name: Run Tests
      run: npm test --if-present
      continue-on-error: true

    - name: Build Backend
      run: npm run build

  deploy-docs:
    runs-on: ubuntu-latest
    name: Deploy Documentation
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'workflow_dispatch' && !inputs.skip_deploy)
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        force_orphan: true
